# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api

GET {{baseUrl}}

###
POST {{baseUrl}}
Content-Type: application/json

  {
    "name_of_project": "Death Note",
    "type_of_project": "Episodic",
    "date": "3-03-2023",
    "location": "Pearl Studios",
    "union_status": "true",
    "casting_office": "Netflix",
    "casting_dir": "Manny Frampton",
    "casting_associate": "Martha Goodman",
    "prep": "pages 4-8",
    "post_aud_notes": "It went well! "
  }
 
###
PATCH {{baseUrl}}/63f8c360344fddcb3db03622
Content-Type: application/json

 {
    "name_of_project" : "New Edit",
    "location" : "New Location"
  }
###

DELETE {{baseUrl}}/63f67c18c30b4d7888926f48
Content-Type: application/json 

###
