# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api

GET {{baseUrl}}

###
POST {{baseUrl}}
Content-Type: application/json

  {
    "name_of_project": "Edit 1",
    "type_of_project": "Edit 2",
    "date": "Edit 3",
    "location": "Edit 4",
    "union_status": true ,
    "casting_office": "Edit 5",
    "casting_dir": "Edit 6",
    "casting_associate": "Edit 7",
    "prep": "Edit 8",
    "post_aud_notes": "Edit 9"
  }
 
###
PATCH {{baseUrl}}/63f79af8f9db7c96c92e8348
Content-Type: application/json

 {
    "name_of_project" : "New Edit",
    "location" : "New Location"
  }
###

DELETE {{baseUrl}}/63f67c18c30b4d7888926f48
Content-Type: application/json 

###
